-- liquibase formatted sql
-- changeset klikli:1
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR DEFAULT 'USER'
    image_id   BIGINT REFERENCES image (id)
);

-- changeset MGubina:1
CREATE TABLE ads
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT,
    price       INTEGER,
    title       TEXT,
    user_id     BIGINT REFERENCES users (id)
    image_id        BIGINT REFERENCES image(id)
);
-- changeset ilya:1
CREATE TABLE comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdAt TIMESTAMP,
    pk        INTEGER,
    text      TEXT NOT NULL,
    user_id   BIGINT REFERENCES users (id),
    ad_id     BIGINT REFERENCES ads (id)
)
